
# Enable or disable sanitizers
sanitisers=true

# Enable or disable instrumentation
[instrumentation]
#https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/README.laf-intel.md
laf = true

#https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/README.cmplog.md
cmplog = true 
cmplog_options = ["", "2AT", "3ATX"]

[secondary_options]
old_queue_cycle = 0.1
disable_trimming = 0.6

explore_strategy = 0.4
exploit_strategy = 0.2

ascii_type = 0.3
binary_type = 0.3

#None means just 1
[power_schedule]
#explore = 1
fast = 0
#exploit = 1
seek = 0
#rare = 1
mmopt = 0
#coe = 1
#lin = 1
#quad = 1